### PR TITLE
Bump PHP to 8.1

### PR DESCRIPTION
**Pull request by wow-apps**
# Solving issue #42 

Making #39 deprecated

### CODE REVIEW

**Comment by skjnldsv** [comment]
@muglug @Nyholm @Taluu @simPod @orklah is this repo still maintained? :)
Thanks and have a great day! :tada:

**Comment by Nyholm** [comment]
It is only Matthew that has write access as far as I know. He left Vimeo. I haven't seen any other Psalm maintainers here. 

FYI, A lot has happened since this action was published. You may get some inspiration from here. 

```yaml
  psalm:
    name: Psalm
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: apcu, redis
          coverage: none

      - name: Download dependencies
        uses: ramsey/composer-install@v2

      - name: Psalm
        run: vendor/bin/psalm --no-progress --output-format=github
```

**Comment by orklah** [comment]
Hey :)

I do have maintainer access here. I did not merge yet because I don't actually know very much about this repo and I was waiting to see if another maintainer would respond

I'm a bit surprised that the solution to a parse error would be to upgrade php here. When Psalm analyze the code, it should do it in the correct PHP version, and out of Psalm's analysis, composer should take the lead to prevent using packages that are not compatible.

I'm not against merging in principle but I'd like to understand what's going on !

**Comment by orklah** [comment]
Thanks!

**Pull request merged**
