### PR TITLE
Allow to specify no dev or ignore platform

### LINKED ISSUE #16: Be able to use it with PHP extensions
Hi, using this action with some packages that require PHP extensions does not work because they don't get installed: https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/runs/1251936295?check_suite_focus=true#step:4:11

It would be nice to have a way to be able to install extensions or [to ignore platform requirements](https://github.com/OskarStark/phpstan-ga/pull/25).

### PR DESCRIPTION
**Pull request by Nyholm**
This will fix #16. 

It is from @OskarStark: https://github.com/OskarStark/phpstan-ga/blob/0.12.52/entrypoint.sh#L9-L17

### CODE REVIEW

**Comment by muglug** [comment]
Thanks!

**Comment by Nyholm** [comment]
Thank you for merging

**Comment by nederdirk** [comment]
Oof, this broke our build (https://github.com/marketphase) pretty hard, since the default suddenly changed from 'install including dev-dependencies' to 'install excluding dev-dependencies' :crying_cat_face:

**Comment by Nyholm** [comment]
Im sorry about that. 

Did you see how to get back the old behaviour?

```diff
+     env:
+       REQUIRE_DEV: true
```

**Comment by nederdirk** [comment]
> Im sorry about that.
> 
> Did you see how to get back the old behaviour?
> 
> ```diff
> +     env:
> +       REQUIRE_DEV: true
> ```

thanks! I added that to our downstream docker image (we need some PHP exts, so we're building on this one)

**Pull request merged**
