### PR TITLE
Bump the PHP version

### PR DESCRIPTION
**Pull request by MrMadClown**
Bump the php Version to 8.0

Maybe this could be a 4.0

### CODE REVIEW

**Comment by orklah** [comment]
I could merge that but I kinda lack hindsight on the effects of changing it

Could you describe the reasons for this change?

Is it simply to modernize the CI or is there more to it? And is there a reason to think it would affect users (thus making a new major release needed)?

**Comment by MrMadClown** [comment]
Hi, it's just to modernize it, since PHP 7.4's end of life was last November.
There was a ton of breaking changes between 7.4 and 8.0 I assumed it would break the CI of users who still run on 7.4

**Comment by orklah** [comment]
But If my understanding on Docker is correct, this won't affect other CI jobs, only this one, right? So it shouldn't make a difference for users

**Comment by MrMadClown** [comment]
Yes, not other CI Jobs, but the Psalm one,  or is it possible to run Psalm with PHP 8.0 on a 7.4 codebase? If so, this would not be worth a new major version.

**Comment by weirdan** [comment]
>  is it possible to run Psalm with PHP 8.0 on a 7.4 codebase?

It is. Specify the version in Psalm config or let it detect it based on your `composer.json`

**Comment by MrMadClown** [comment]
Nice so the 8.0 bump for the docker image doesn't affect other users.

**Comment by orklah** [comment]
superseded by #43 Thanks!

**Pull request closed without merging**
