### PR TITLE
Fold "composer install" into a group

### PR DESCRIPTION
**Pull request by Nyholm**
This is inspired by https://github.com/OskarStark/phpstan-ga

### CODE REVIEW

**Comment by Nyholm** [comment]
Friendly ping

**Comment by muglug** [comment]
Sorry!

**Comment by Nyholm** [comment]
Thank you for merging.

**Comment by Nyholm** [comment]
Oh, no... Im sorry.

This will generate an error if there is no composer vendors...
```
/composer/vendor/bin/psalm --version
```

It shoudnt... but this PR broke master.. I added #12 to fix this.

**Pull request merged**
